name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        ## limits ssh access and adds the ssh public key for the user which triggered the workflow
        limit-access-to-actor: true
        ## limits ssh access and adds the ssh public keys of the listed GitHub users
        limit-access-to-users: MaxBo
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gertzgutscheruemenapp/osrm-flask:$(date +%s)
    - name: Test with pytest
      run: docker run gertzgutscheruemenapp/osrm-flask:$(date +%s) pytest
